// <auto-generated />
using System;
using DataProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ProjectMain.Migrations
{
    [DbContext(typeof(SimpleDbContex))]
    partial class SimpleDbContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProjectMain.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("Userid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Userid");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("ProjectMain.Models.Recipie", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("AccountId");

                    b.ToTable("Recipies");
                });

            modelBuilder.Entity("ProjectMain.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AccountHolderid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("AccountHolderid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectMain.Models.Account", b =>
                {
                    b.HasOne("ProjectMain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("Userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectMain.Models.Recipie", b =>
                {
                    b.HasOne("ProjectMain.Models.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ProjectMain.Models.User", b =>
                {
                    b.HasOne("ProjectMain.Models.User", "AccountHolder")
                        .WithMany()
                        .HasForeignKey("AccountHolderid");

                    b.Navigation("AccountHolder");
                });
#pragma warning restore 612, 618
        }
    }
}
